#!/bin/sh

set -e

lb config noauto \
	--linux-packages linux-image-rt \
	--distribution buster \
	--binary-images iso-hybrid \
	--debian-installer live \
	--archive-areas "main contrib non-free" \
	--iso-application "LinuxCNC-2.8.3" \
	--iso-preparer "emc-developers@lists.sourceforge.net" \
	--iso-volume "LinuxCNC_2.8.3" \
	--image-name "LinuxCNC_2.8.3" \
	--iso-publisher "www.linuxcnc.org" \
	--apt-recommends true \
	--parent-mirror-bootstrap http://deb.debian.org/debian \
	--parent-mirror-binary http://deb.debian.org/debian \
	--parent-mirror-chroot-security http://deb.debian.org/debian-security \
	"${@}"
