#!/bin/sh

set -e

lb config noauto \
	--linux-packages linux-image-rt \
	--distribution bookworm \
	--binary-images iso-hybrid \
	--debian-installer live \
	--archive-areas "main contrib non-free-firmware" \
	--iso-application "LinuxCNC-2.9pre1" \
	--iso-preparer "emc-developers@lists.sourceforge.net" \
	--iso-volume "LinuxCNC_2.9pre" \
	--image-name "LinuxCNC_2.9pre" \
	--iso-publisher "www.linuxcnc.org" \
	--apt-recommends true \
	--security false \
	--updates false \
	--parent-mirror-bootstrap http://deb.debian.org/debian \
	--parent-mirror-binary http://deb.debian.org/debian \
	--parent-mirror-chroot-security http://deb.debian.org/debian-security \
	"${@}"

# Debian 12 strips out non-free if it exists and also removes non-free-firmware if installed to HDD
